### ISSUE TITLE
Can’t select party type

### ISSUE THREAD

**Issue by meomancer** [Cadasta/cadasta-qgis-plugin#108]
# Problem
Oliver's question:

> When creating a new project from existing data, I can’t select party type (among others) if they are in a separate table. I have to talk to our programs team if that’s a valid use case at all, there’s a chance that people just have shape files with all information in it. So, there’s nothing to do for you at this point.

**Comment by SteadyCadence** [comment]
This brings up a larger discussion.  With the current workflow, a user has to join both the relationships and party files to the location files (which can be up to three).  It's a little bit of work to simply get all of the fields in one file.  It would be nice if we could automatically have those JOINs in place.  Is that possible?

**Comment by cchristelis** [comment]
This will be solved with documentation.
