### ISSUE TITLE
Party attributes are not downloaded

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-qgis-plugin#116]
When I download a project for editing, party attributes don't show up in the parties table. There is a field `attributes` but it's empty. I used my [Leipzig Project](https://platform-staging-api.cadasta.org/organizations/olivers/projects/leipzig/) for testing. 

I would expect that all attributes for a party are present; with each attribute in its own separate field.

**Comment by dimasciput** [comment]
Hi @oliverroick Can you share the account for that project? So we can download and test it.

**Comment by oliverroick** [comment]
No I won't share my account with you ;) But I can add you to that project if you give me the username of your account. Send it via email though

**Comment by dimasciput** [comment]
Great! Email sent.

**Comment by dimasciput** [comment]
@oliverroick can you test the plugin again, I uploaded in plugins.kartoza.com with version 1.0.3

**Comment by SteadyCadence** [comment]
This works now.
