### ISSUE TITLE
Title Cut off in Create New Project

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-qgis-plugin#125]
The top title "Cadasta Step by Step" is cut off when creating a new project. 

![image](https://cloud.githubusercontent.com/assets/67992/25154174/6bc2af6c-2444-11e7-98ed-2ce61785d0e0.png)

**Comment by cchristelis** [comment]
I'm not able to reproduce this on my machine. @dimasciput perhaps check on a non-mac device as @wonderchook is using WIndows...
