### ISSUE TITLE
Project URL Should not be Required

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-qgis-plugin#126]
Currently when creating a project "Project URL" is a required field. This should be optional.

**Comment by cchristelis** [comment]
@wonderchook, could you assign this to @dimasciput please, it seems like I don't have adequate​ permissions.

**Comment by SteadyCadence** [comment]
The required "Project URL" shows up a few times-- in the "Create Project" window and the "Update Project" window.
