### ISSUE TITLE
More detailed error messages

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-qgis-plugin#128]
When a record fails to upload it just says error. More information would be helpful. Such as the error from the api (if there is one) and which record failed. 

![image](https://cloud.githubusercontent.com/assets/67992/25154851/35ee657c-2447-11e7-9857-148f91ccb0d1.png)

**Comment by wonderchook** [comment]
@oliverroick is there an error returned more than a 400?

**Comment by cchristelis** [comment]
@dimasciput let's add the text: `Server responded with <<status code>>`

**Comment by oliverroick** [comment]
If a `400` error is returned there should be an error message describing what went wrong.
