### ISSUE TITLE
User not signed in is able to view public projects

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-qgis-plugin#129]
I've installed the Cadasta QGIS plug-in today and was never prompted for a username or password.  I can see all the projects in demo.  It seems like I should have had to enter credentials to access only my projects.

My Cadasta > Options screen:

<img width="880" alt="screenshot 2017-04-18 21 07 46" src="https://cloud.githubusercontent.com/assets/1119621/25160374/53010258-247b-11e7-9358-297dc9c7916d.png">

I can see all the projects:

<img width="889" alt="screenshot 2017-04-18 14 34 02" src="https://cloud.githubusercontent.com/assets/1119621/25160394/69d8e964-247b-11e7-864d-c5e60d233cdb.png">

**Comment by dimasciput** [comment]
I think those are public projects, you will able to see it without having to login first.

**Comment by SteadyCadence** [comment]
I think we should discuss this.  I would think that there are some organizations that only want to see their projects.  

It seems a bit strange to let them see all public projects without having an option to indicate if they want that. 

I think we should have a checkbox, like 

- [ ] Include Cadasta public projects

**Comment by cchristelis** [comment]
I agree with @SteadyCadence, please move this to ready if we need to action on this...

**Comment by clash99** [comment]
I think this list should only include active projects and not archived projects.

**Comment by cchristelis** [comment]
# Proposed solution

Add a checkbox (default unselected) `Include all Cadasta public projects`. (This will be updated later). Users should only see projects that they can "do stuff" on.

**Comment by cchristelis** [comment]
# Proposed solution 2

Filter public projects, by downloadable ones on download and createable ones on create
.
