### ISSUE TITLE
Move "Contact" option

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-qgis-plugin#135]
We want the QGIS plugin to focus on import/export of data.  If users need to adjust/add the contact information I think we should have them do so on the web.

**Comment by cchristelis** [comment]
@SteadyCadence, this does seem like a useful option for users, who are creating projects. Perhaps this is less useful on edits?

**Comment by cchristelis** [comment]
We will determine where to...

**Comment by clash99** [comment]
**- Remove Contact as top level menu item**

![contacts menu](https://cloud.githubusercontent.com/assets/1119621/25240518/a62378c4-25b8-11e7-98ce-2c3106aa9803.png)


**- Include edit contact button and put edit contact functionality in new window similar to questionnaire editing**

![edit contacts](https://cloud.githubusercontent.com/assets/1119621/25248379/afca9f04-25d3-11e7-8318-577fc5913c8b.png)

**Comment by cchristelis** [comment]
is this duplicated in #150

**Comment by clash99** [comment]
#150 is adding the additional fields.  This one is detailing the contact editing functionality.  So definitely related.  Please organize them into one if that is easier.
