### ISSUE TITLE
List of Renames/Vocabulary Adjustments

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-qgis-plugin#137]
- [x] On the main menu, let's change "Options" -->  "User Settings" or or "User Preferences" (or without the "User")
- [ ] On "Options" window, let's change "Test Connection" to "Login"
- [ ] Re-write instructions on "Help"... few spelling errors and I think we should focus on use cases... ways to set up layers, etc.  (I think we should make the current instructions intuitive in the UI)

Needs Discussion: 
- [ ] Add to "About" option
- [ ] Move "Contacts" option --> #135

**Comment by cchristelis** [comment]
@SteadyCadence, on "Options" window, let's change "Test Connection" to "Login". I would like some clarity on this, as the `Test Connection` just asserts the validity of the credentials. The idea of a login is captured in the `Save`.

**Comment by cchristelis** [comment]
Hi @SteadyCadence, on point 3, are you proposing we make embed the help text in the various UI components?

**Comment by SteadyCadence** [comment]
Hey @cchristelis, I think if we could push the UI to look more like the proposed designs that you all included then we will not need some of the instruction included in the Help section:

![screen shot 2017-04-19 at 1 05 02 pm](https://cloud.githubusercontent.com/assets/25337622/25197299/dc42e588-2500-11e7-9329-be16cbf9cb04.png)

**Comment by SteadyCadence** [comment]
For the "Login" change, I understand that "Test Connection" makes more sense when understanding the back end code.  However, I think that "Test Connection" sounds very intimidating to those that are non-technical.  I think something more common will make it easier for others to understand.

**Comment by cchristelis** [comment]
@SteadyCadence, what I mean is that if we click `Save` the `Login` action is performed, so renaming `Save` to `Login` and `Delete` to log out is correct. If `Test Connection` sounds too techie, why don't we go with `Verify Details`?
