### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-qgis-plugin#145]
Update the About Text to include information about who/what Cadasta is

**Comment by cchristelis** [comment]
could someone please add that text here

**Comment by wonderchook** [comment]
@SteadyCadence is this something you can either write or coordinate with @bethschechter

**Comment by SteadyCadence** [comment]
Sure. I can take the lead. I may use previous content from pamphlets.

**Comment by wonderchook** [comment]
@SteadyCadence yes, I don't think it needs to be rewritten. There is plenty of existing content.

**Comment by SteadyCadence** [comment]
@cchristelis What is the best way to provide some formatting and images?  I think it would be nice to include an image of the platform to make it clear that the web interface is where all the information gets collected and stored. 

Here's the copy:

# About Cadasta

The Cadasta Foundation, a non-profit organization, is a global community of technologists and land sector experts that harness innovative technology to document and strengthen land and resource rights. Cadasta develops and supports innovative digital tools, such as this QGIS plugin, to help its partners document, store, and analyze information about people’s relationship to land and natural resources. The technology we use and develop is provided under an open source license which means it can be modified as the project changes or partners’ needs change. 

Our suite of tools-- focused around our web platform on https://platform.cadasta.org-- permits users to create digital records of land and resource rights data. Information can be collected through traditional paper-based surveys and maps, GPS coordinates, footage from drones, digital maps, video interviews, photographs, paper attestations, tax receipts, and other supporting documentation. The Cadasta platform aims to:

• Incrementally establish evidence of formal or customary land rights – even in the
absence of government support
• Survey and document the land use and rights of women and other vulnerable groups
• Inform, plan, and deliver urban resilience strategies for governments’ most
at-risk citizens
• Certify sustainable farms and commodity production
• Identify factors undermining increased productivity
• Identify overlapping claims and potential conflicts over land and resources
• Document and monitor natural resource concessions and extractive industries
• Conduct research and advocacy for land rights as a cross-sectoral development issue

The platform follows a stringent privacy protocol, certifies the security of the platform, and makes no claims to rights to our partners’ data. Cadasta is a strong advocate for government adoption of open data policies for land rights data. We are active contributors to the Global Open Data Index on land, as well as transparency and accountability initiatives of the Open Government Partnership. That said, our partners determine whether and how the data they collect is shared.

Thanks to generous funding from UK aid, Omidyar Network, and other funders, large and small, we can provide many of our services to partners free of charge.

**Comment by bethschechter** [comment]
@SteadyCadence if you write a thing and want a review, just say the word. That said, looks like you've got what you need above.
