### ISSUE TITLE
Step two of project creation wizard should have defaults

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-qgis-plugin#146]
Right now it isn't clear how to not select a Party Type, Party Name or Relationship Type which are not required. There should be a default which is not a selected field. That says "Select Column"

![image](https://cloud.githubusercontent.com/assets/67992/25236995/3ed7090c-259e-11e7-9008-c4f369e6e6d8.png)

**Comment by cchristelis** [comment]
could we change the `no field` option to `--------- no field ----------`

**Comment by cchristelis** [comment]
Let's update the error text to read: "Location type field is required please select." Attach to field if possible.
