### ISSUE TITLE
Project details

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-qgis-plugin#150]
Include more project details after selecting project.  Should be:

- Project Name
- Project Description
- Project URL
- Project Contacts (with ability to edit from here #135 )
- Privacy Setting (for Public/Private)

**When downloading project or updating a project, make changes to this screen:**

<img width="885" alt="screenshot 2017-04-20 09 59 01" src="https://cloud.githubusercontent.com/assets/1119621/25238547/5fc69190-25b3-11e7-8a36-ebb9803f66a4.png">

**Similar to this:**

![add project details](https://cloud.githubusercontent.com/assets/1119621/25248609/7d207082-25d4-11e7-94a0-93f8f21088b3.png)

**Comment by cchristelis** [comment]
maybe rather call it "My Contacts", since we can't edit all the contacts that we can download?

**Comment by clash99** [comment]
You can't edit all the contacts? only add new ones?  If so, then we should call the button "Add Contacts" instead of "Edit Contacts".  Does that seem right?
