### ISSUE TITLE
WIP: Change text on "test connection" button

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-qgis-plugin#151]
- Change button text to "Verify credentials"
- Change button text while processing to "Verifying..."
- Change second sentence at top to read 'verify credentials' in place of 'test connection'.

![test connection](https://cloud.githubusercontent.com/assets/1119621/25241672/77a7b3bc-25bc-11e7-829c-3355914ea3bc.png)

**Comment by clash99** [comment]
Leaving as-is for now, closing issue.

**Comment by cchristelis** [comment]
I actually quite like this text change...
