### ISSUE TITLE
Is it possible to force the spatial_id, party_id and relationship_id columns to be read only?

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-qgis-plugin#152]
I was updating a table and clicked on the party_id column where I accidently typed in a different value.

Does QGIS allow some columns to be READ-only in tables?

**Comment by cchristelis** [comment]
It does not seem possible, like with most DB's provide permissions at the table level, not at the column level.

**Comment by cchristelis** [comment]
Closing since this is not possible.
