### ISSUE TITLE
Add web link to help

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-qgis-plugin#165]
Create link in Cadasta docs to link from within the help section of the plugin.

**Comment by cchristelis** [comment]
Hi @SteadyCadence and @wonderchook, could we please have the link that you inted to use. We'd like to update the plugin accordingly.

**Comment by MappingKat** [comment]
You can use this link: https://docs.cadasta.org/en/11-qgis-plugin.html (though that is the English version).

**Comment by bethschechter** [comment]
you beat me to the link @MappingKat!
