### ISSUE TITLE
Advanced Questionnaire JSON :: Include Dev and Index for JSON

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-qgis-plugin#176]
Need to include what the abbreviations mean in the type column (GT=> geometry, S1=> select_one,IN=> integer, DT=> date, etc)

Also, need to include how to change a text field into a select_one or select_multiple with the json.

**Comment by MappingKat** [comment]
We need to link the references tables from this docs to the Advanced json settings: https://cadasta.github.io/api-docs/#questionnaires
