### ISSUE TITLE
Create Project :: Add GUI step for being able to choose which entity (location, party, relationship)  a field goes into

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-qgis-plugin#186]
Technically, you can do this in the json.... we need a step to be able to choose with entity a field gets stored in.

For example, when I upload a file with "gender" information there is no way for me to make sure that gets put into the party entity.

**Comment by wonderchook** [comment]
Is this a duplicate of #180 ?

**Comment by SteadyCadence** [comment]
yep. I guess I got really excited about that option...
