### ISSUE TITLE
DateTime fields are not included in the JSON questionnaire schema

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-qgis-plugin#191]
When I try to uploading the attached file the locations fail, it appears because the column date_n_time isn't added to the questionnaire schema. This seems to be happening for all DateTime. 

[bad-date-file.zip](https://github.com/Cadasta/cadasta-qgis-plugin/files/975117/bad-date-file.zip)

**Comment by dimasciput** [comment]
@wonderchook fixed on latest PR https://github.com/Cadasta/cadasta-qgis-plugin/pull/192
