### ISSUE TITLE
Advanced questionaire edits always bring up platform errors

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-qgis-plugin#194]
Whenever I make edits to the json in the "Advanced" settings in "Create Project", I always get errors.  Can we get that tested some more?

This is not 100% related, but can we remove the index property in the json and assign that after the data is submitted.

**Comment by dimasciput** [comment]
What errors? Sometimes the error happens in cadasta backend. 

> This is not 100% related, but can we remove the index property in the json and assign that after the data is submitted.

We can, but why do we need this?

**Comment by SteadyCadence** [comment]
I am going to divide this topic into two issues: (1) cleaning up the parameters that we have listed in the json and (2) making sure that certain scenarios are supported with the create project step.
