### ISSUE TITLE
Unable to login on staging with proper username and password

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-qgis-plugin#202]
Not sure what's going on, but the "Clear" button isnt activating and I can't log into any of the accounts. 

When I click on the "User Settings", the "https://platform.cadasta.org" url is filled in.  Nothing else.  I changed the url to "https://platform-staging.cadasta.org" and then fill out my user name and pw.  Click "Test Connection" and it fails.

The "Clear" button is never activated-- always greyed out.

**Comment by SteadyCadence** [comment]
Finally got `demo` to work, but not `platform` or `staging`

**Comment by SteadyCadence** [comment]
Either way there are no error messages or ways to clear out what the issue is... really frustrating.

**Comment by dimasciput** [comment]
I think this is because the api from the server has changed, did you test the latest build that has @alukach commits?

**Comment by dimasciput** [comment]
@SteadyCadence this is the PR → https://github.com/Cadasta/cadasta-qgis-plugin/pull/154

**Comment by alukach** [comment]
@steadycadence, @dimasciput, We've deployed pagination to all Cadasta API list endpoints on the staging server. This effectively broke the QGIS plugin, requiring us to merge PR #154. Currently pagination is not deployed to `platform` or `demo`. You should be able to still use the old version of the plugin with those systems. To use `staging`, you will need to install the plugin from the `develop` branch of this repo.

With that said, I'm not certain as to how pagination would break login, as that is not a list-endpoint. Can you please post the error logs?

**Comment by dimasciput** [comment]
@alukach the login itself is fine, but in the plugin after user login and save the token there is a process that fetch the organization of the user and save it locally.

**Comment by SteadyCadence** [comment]
I created a new user account, restarted QGIS and finally was able to log in. 

I did get this error message:

```2017-05-22T09:24:15	1	Traceback (most recent call last):
File "/Users/katrinaengelsted/.qgis2/python/plugins/cadasta-qgis-plugin/cadasta/gui/tools/widget/options_widget.py", line 193, in save_authtoken
			    self.save_organizations()
File "/Users/katrinaengelsted/.qgis2/python/plugins/cadasta-qgis-plugin/cadasta/gui/tools/widget/options_widget.py", line 209, in save_organizations
			    organization.append(result['slug'])
TypeError: string indices must be integers
```

**Comment by wonderchook** [comment]
@SteadyCadence delete the plugin and reinstall or delete the pyc files in the plugin folders.
