### ISSUE TITLE
Download Projects :: Default is to still download all public projects

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-qgis-plugin#203]
The checkbox is unchecked but all public projects are still being downloaded.

**Comment by dimasciput** [comment]
I just tested it, and I can't reproduce the bug. It's just pulling the private project for me, can you recheck it?

**Comment by cchristelis** [comment]
@SteadyCadence, could you please confirm that this is the case with the latest plugin. @dimasciput, could you please let us know when the plugin is updated on the kartoza repo.

**Comment by cchristelis** [comment]
Hi @SteadyCadence, could you please update your checkout of the plugin from:
`http://www.kartoza.com/en/plugins/qgis_plugin/` and confirm that this is still a bug.

**Comment by SteadyCadence** [comment]
Apologies for the delay.  There is still something funky going on with the "public projects" checkbox.  When I click it on, it pulls down all of the private projects I am a member to.  When it is unclicked it does not list any projects I am apart of on `platform`- public or private.

I can't test `demo` or `staging` because the "User Settings" window won't let me clear the auth token.  Being able to sign in and out of databases is a little tricky.

**Comment by SteadyCadence** [comment]
There is still something going on with the public projects check box (ie #217).  I am not sure if this issue is still occurring or if it is something else.
