### ISSUE TITLE
Support for non-Roman language

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-qgis-plugin#205]
When you pull down a project, the table lists the "names", or keys, of the fields. That is fine for roman languages, but does not work for languages with different scripts, like hindi, arabic, etc.

We need to be able to show the label of fields in that case. Also, it looks cleaner overall.

**Comment by dimasciput** [comment]
We haven't support non roman languages, it was never in requirement. I think this is count as enhancement feature.

**Comment by dimasciput** [comment]
We have fixed this in this PR - https://github.com/Cadasta/cadasta-qgis-plugin/issues/213

@SteadyCadence, Can you test it again, and update this issue? Thanks

**Comment by SteadyCadence** [comment]
Can you explain what solution you used?  I am not sure what I should be testing?

**Comment by dimasciput** [comment]
@SteadyCadence we can create a project with non-roman language : 
<img width="959" alt="screen shot 2017-08-08 at 9 43 48 am" src="https://user-images.githubusercontent.com/1979569/29054107-24926e34-7c1e-11e7-8aaf-73328fa215e0.png">
