### ISSUE TITLE
User Settings :: "Clear" Button does not reset

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-qgis-plugin#214]
I signed into `platform` to pull down a project.  During that same QGIS session, I also wanted to pull down a project from staging. 

# Steps to reproduce
1. Sign into `platform` successfully.
2. Go back to "User Settings" and notice the "Clear" button is greyed out. 
3. Fill out User Settings and the session fails.

I need to be able to hit "Clear" in order to log into another database and the clear button does not reset.

**Comment by SteadyCadence** [comment]
Can we make the "Clear" button always active?  There is no instance where it should not be greyed out as it causes the user to get stuck without being able to change the URL, password, or username.

**Comment by SteadyCadence** [comment]
The "Clear" button is much better, but that clear button does not reset a Failed login. See video:
![login-issues](https://user-images.githubusercontent.com/25337622/28658316-558dcd36-72b3-11e7-9f04-50c1422082fb.gif)

**Comment by dimasciput** [comment]
@SteadyCadence ah ok, I will remove the `Failed` message

**Comment by dimasciput** [comment]
@SteadyCadence please check from the develop branch again, I have updated the develop to fix this issue

![cadasta](https://user-images.githubusercontent.com/1979569/28902495-62263ef4-7829-11e7-8fd4-5c98582e3f4b.gif)

**Comment by SteadyCadence** [comment]
I think that this can be closed as the clear button does reset.  And this is solving the forgotten password problem that partners run into.  

There does seem to still be an issue when you click "Clear" when trying to change the URL.  Steps to repeat: 

1. Edit the URL (`demo` from `platform`)
2. Enter in username and password
3. Hit "Submit"
4. Enter URL and username/password and login still fails.

**Comment by dimasciput** [comment]
It works for me

![cadasta](https://user-images.githubusercontent.com/1979569/29054717-ff6c5fe4-7c21-11e7-8151-60386a0a78b7.gif)
