### ISSUE TITLE
Create wizard for project creation

### ISSUE THREAD

**Issue by ismailsunni** [Cadasta/cadasta-qgis-plugin#22]
See the wireframe below for the guidance:

![project_creation_wizard](https://cloud.githubusercontent.com/assets/1421861/21306429/8745e938-c603-11e6-8f0b-6eef8226102d.png)

**Comment by timlinux** [comment]
And note again that there should be an additional panel for selection of a questionairre.

**Comment by dimasciput** [comment]
Got an issue on this, still asking the cadasta guy

I tried to create a new party using this API : https://platform-staging-api.cadasta.org/api/v1/organizations/follow-the-light/projects/ftl18/parties/
This is the POST body data
```
{
    "name": "PartyTest",
    "type": "IN",
    "attributes": {
        "name": "TEST ATTR"
    }
}
```
And I got this result :
```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
    "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
    <head>
        <title>Platform Error</title>
    </head>
    <body>
        <h1>Platform Error</h1>
        <p>We're sorry, our platform encountered an error while processing your request.</p>
        <p>Our developers have been notified.</p>
    </body>
</html>
```

**Comment by dimasciput** [comment]
Got a response, he said that it tries to validate the “name” field in "attributes" field and if you haven’t created the questionnaire that defines the name field if fails, and if you leave “attributes” empty it should work.

So basically we need to upload questionnaire first before mapping the "attributes", I think I will remove/hide "attributes" field for now and let them test it.

**Comment by cchristelis** [comment]
@dimasciput and @meomancer, so every attribute that is not a default, will end up in the questionnaire.

**Comment by cchristelis** [comment]
This ticket will be finished by #71.
