### ISSUE TITLE
(WIP) Create Project :: Remove "Hardcoded Json" Text in Advanced JSON editing settings

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-qgis-plugin#224]
There are a few instances where there seems to be some json hard coded into the "create project" submission. 

<img width="311" alt="screen shot 2017-07-19 at 5 22 40 am" src="https://user-images.githubusercontent.com/25337622/28348019-5afb2a96-6c43-11e7-890a-7a30596ca60a.png">

Index? Can that be assigned after the json submission?

**Comment by cchristelis** [comment]
fixed by #249
