### ISSUE TITLE
Create wizard for updating a project

### ISSUE THREAD

**Issue by ismailsunni** [Cadasta/cadasta-qgis-plugin#23]
See wireframe below for the guidelines:
![project_update_wizard](https://cloud.githubusercontent.com/assets/1421861/21306525/fbf21536-c603-11e6-8f1f-fc6433d93520.png)

**Comment by dimasciput** [comment]
This is for updating project basic information : https://github.com/kartoza/cadasta-qgis-plugin/pull/67

I'm still confused on how to update the locations/spatial data.

**Comment by cchristelis** [comment]
This is done except for the Questionnaire, which will be followed up in #75.
