### ISSUE TITLE
Use master branch as main branch for QGIS plugin repo

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-qgis-plugin#232]
The plugin is in the QGIS repo!  Woot woot!  

However, there are some text changes that I added-- namely "Test Connection" to "Connect" and the help docs.

**Comment by SteadyCadence** [comment]
@dimasciput can you write out your workflow?  I want to be fast at testing out fixes and need to know how you are working. 

Are you working on the `develop` branch and then updating that to the QGIS main repo? 

Can we merge everything to the `master` branch and push that up.  I want `master` to be the main branch we use.

**Comment by SteadyCadence** [comment]
Can someone on Kartoza write down the process they are using for fixing bugs and publishing to the QGIS plugin?

It looks like `develop` is the only branch being worked on.  I would like to make some changes to the code base and want `master` to be the final branch.

**Comment by cchristelis** [comment]
Let's start tagging as we release to the plugin repository.
