### ISSUE TITLE
Auto-close windows when completed (ie data download or submitted)

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-qgis-plugin#235]
Some partners do not realize that they need to close the windows when the data has downloaded. They assume that it will close when it is done.  

I think we should auto-close the windows when the data has been downloaded and/or submitted.

**Comment by dimasciput** [comment]
Updated in https://github.com/Cadasta/cadasta-qgis-plugin/pull/241

**Comment by SteadyCadence** [comment]
The auto-close works well! 

However, it seems that the "Close" button is greyed (de-activated) out now. It never seems to activate. Should we just remove it?  Or can we get it to activate again?

**Comment by dimasciput** [comment]
The close button is still active in create project : 
![screen shot 2017-08-11 at 1 24 13 pm](https://user-images.githubusercontent.com/1979569/29203113-6f1be792-7e98-11e7-836c-a522aaeda138.png)

**Comment by SteadyCadence** [comment]
Ah interesting. In the Download Project, it is greyed out but still works.  Can you fix the Download Project "Close" button to be active?  Then this issue is ready to go.
![Screen Shot 2017-08-15 at 11.53.29 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5984ee90306630001f9a6908/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6455f66b7191a379ee0c2e52415d47bc21254d58eeb9cb74fce36f34985619e8d9685877906814abbf8319be55b8748b4f8cb5e98d45c9fa2137a5dad11b61435c52dcbd4f3fb29a4ac259f34be34550a1153260e276376e0a.png)

**Comment by dimasciput** [comment]
@SteadyCadence updated (https://github.com/Cadasta/cadasta-qgis-plugin/pull/250). Please try again.

**Comment by dimasciput** [comment]
@SteadyCadence can you test this issue?

**Comment by SteadyCadence** [comment]
I'm still getting a greyed out close button.

**Comment by SteadyCadence** [comment]
It seems to work for some instances and not others. I am not sure if its the different URLs (demo versus staging) or the different projects.

**Comment by dimasciput** [comment]
What do you mean by others? Have you update your plugin?
