### ISSUE TITLE
Remove index and constraint from json properties in "create project"

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-qgis-plugin#243]
I want to keep the json schema as simple as possible.  We can remove "index" and "constraint" from the field objects. 

Also, please remove this "title" field that shows up on all new projects: 
```        {
            "index": 5, 
            "relevant": null, 
            "name": "title", 
            "constraint": null, 
            "default": null, 
            "hint": null, 
            "required": false, 
            "label": "Cadasta Platform - UAT Survey", 
            "type": "NO"```

**Comment by dimasciput** [comment]
@SteadyCadence If I remove index in questionnaire then I get this error message : 
```
Error 400 : {"question_groups": [{"questions": [{"index": ["This field is required."]}, {"index": ["This field is required."]}, {"index": ["This field is required."]}, {"index": ["This field is required."]}, {"index": ["This field is required."]}]}]}
```

**Comment by oliverroick** [comment]
`index` is required for all questions, question groups and options.

**Comment by dimasciput** [comment]
I remove the index from the advanced view, the index will be added before the questionnaire uploaded.

**Comment by SteadyCadence** [comment]
Perfect, @dimasciput!  I think that works better-- to have the index added after the questionnaire has been edited. 

Thank you!

**Comment by SteadyCadence** [comment]
Looks much cleaner.  Could you also remove this field:   ```{
            "relevant": null, 
            "name": "title", 
            "hint": null, 
            "default": null, 
            "required": false, 
            "label": "Cadasta Platform - UAT Survey", 
            "type": "NO"```
This field is really only for ODK and it is not needed.

**Comment by SteadyCadence** [comment]
I am not sure how the index is being signed. When I tried to add a custom field, I got a 400 error about the index.
![Screen Shot 2017-08-10 at 10.06.46 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5984ee90306630001f9a6908/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6455f36b7191a379ef0c2b57415b48bc21254d58eeb9cb74fce36f34985619e8d9685877906814abbf8319be55b8748b4f8cb5e98d45c9fa2137a5dad11b61435c52dcbd4f3fb29a4ac259f34be34957a0173e66ee72326e0a.png)

**Comment by dimasciput** [comment]
@SteadyCadence Can you copy paste your json here.

**Comment by dimasciput** [comment]
@SteadyCadence are you still having this issue?

**Comment by dimasciput** [comment]
@SteadyCadence have you got any chances to review this?

**Comment by SteadyCadence** [comment]
I don't seem to get that error so I think its fixed.
