### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by ismailsunni** [Cadasta/cadasta-qgis-plugin#25]
We need to create some icon or logo for:

- [x] plugin logo
- [x] setting icon
- [x] project creation icon
- [x] project update icon
- [x] project download icon

**Comment by timlinux** [comment]
See also #48 which supplies the CI materials.

**Comment by meomancer** [comment]
@ismailsunni @timlinux 
on CI materials, there is no project creation, update and download icon
should i ask cadasta team?

**Comment by ismailsunni** [comment]
@meomancer just ask them first, if they don't supply it just make a simple icon for it. For example cadasta icon then overlay with creation symbol, or update symbol, or download arrow symbol.

**Comment by cchristelis** [comment]
Waiting on cadasta to provide this.
