### ISSUE TITLE
Tenure Type 400 errors

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-qgis-plugin#257]
I keep getting 400 errors about `tenure_type` when I update or create projects.  Tenure type and location type are required fields but have dynamic custom fields, so I am not sure if maybe the hard coded values in the plugin are causing the issues... or if its an API bug.

Error 400 : {"tenure_type": ["'CO' is not a valid choice for field 'tenure_type'."]}

**Comment by dimasciput** [comment]
I tried to update with CO value for tenure_type and it's working fine, could you maybe upload your project data with the questionnaire? @SteadyCadence

**Comment by cchristelis** [comment]
Closing this as CNR.
