### ISSUE TITLE
Need to apply Cadasta CI guidelines to all dialogs and user facing elements

### ISSUE THREAD

**Issue by timlinux** [Cadasta/cadasta-qgis-plugin#48]
Please see the attached document which provides their logo and schemes. We should include their logo onto each dialog. Take a look at how we did this in InaSAFE for an example of the user experience we might provide:

![screen shot 2016-12-26 at 8 52 39 am](https://cloud.githubusercontent.com/assets/178003/21477252/ba806aea-cb48-11e6-89a0-40d6c55abab7.png)

![screen shot 2016-12-26 at 8 52 50 am](https://cloud.githubusercontent.com/assets/178003/21477257/bdb5a0ae-cb48-11e6-8a58-62f974491698.png)

Cadasta guidelines are here:

https://drive.google.com/open?id=0B_TBxlUZZaVXUjB6cTUxanBzUkU

**Comment by timlinux** [comment]
Also please update the plugin icon accordingly.

**Comment by meomancer** [comment]
i think this issue is done (client was satisfied with the UI)
