### ISSUE TITLE
Use get_ui_class for ui file.

### ISSUE THREAD

**Issue by ismailsunni** [Cadasta/cadasta-qgis-plugin#6]
For easier development, I suggest we use similar approach to manage the .ui file like in InaSAFE project. In InaSAFE project, we do like this:

- Adapt `get_ui_class` method from here https://github.com/inasafe/inasafe/blob/develop/safe/utilities/resources.py#L82
- Use that method to load the python UI class on runtime like in here: https://github.com/inasafe/inasafe/blob/develop/safe/gui/widgets/dock.py#L137

By doing this, we can avoid the needs to compile the ui file everytime we change the ui file and less file to be submited to the repository.

cc @dimasciput @meomancer

**Comment by timlinux** [comment]
See https://github.com/inasafe/inasafe/wiki/Coding-Standards#qt-guidelines for more detailed explanation of how run-time compilation of UI files is done.

**Comment by meomancer** [comment]
fixed #10
