### ISSUE TITLE
Create Wiki page for Development Setup

### ISSUE THREAD

**Issue by ismailsunni** [Cadasta/cadasta-qgis-plugin#7]
We need to document how we setup the development environment for this project. See some references in:
- https://github.com/inasafe/inasafe/wiki/Development-on-OSX
- https://github.com/inasafe/inasafe/wiki/Development-on-Linux

cc @meomancer @dimasciput

**Comment by timlinux** [comment]
Also copy coding standards doc to there

**Comment by ismailsunni** [comment]
@meomancer can you create wiki for Linux one? I have done for OSX and coding standard. Thanks

**Comment by meomancer** [comment]
https://github.com/kartoza/cadasta-qgis-plugin/wiki/Development-on-Linux
