### ISSUE TITLE
Plugin error in QGIS version 2.8

### ISSUE THREAD

**Issue by meomancer** [Cadasta/cadasta-qgis-plugin#85]
# Problem
Oliver's question:

> Could you provide information about system requirements in the README? Which QGIS version is required? Any dependencies to install? I installed the plugin on QGIS 2.8 and got errors, but everything worked fine with 2.14.

it seems it is related with : https://github.com/kartoza/cadasta-qgis-plugin/issues/84

# Solution
check it in 2.8 and try to fix it

**Comment by oliverroick** [comment]
I can confirm that `from qgis.PyQt import ...` caused problems with 2.8

**Comment by Gustry** [comment]
Note that QGIS 2.8 is not supported anymore by QGIS. We work with both QGIS 2.14 and 2.18 for now.

**Comment by ismailsunni** [comment]
@meomancer you can also set the minimum QGIS version here https://github.com/kartoza/cadasta-qgis-plugin/blob/develop/metadata.txt#L11

**Comment by cchristelis** [comment]
@oliverroick, are you happy with use supporting  >= 2.14?

**Comment by oliverroick** [comment]
Supporting 2.14 and upwards is ok. 2.14 is the current LTS after all.
