### ISSUE TITLE
Confusing update wizard

### ISSUE THREAD

**Issue by meomancer** [Cadasta/cadasta-qgis-plugin#87]
# Problem
Oliver's question:

> The project update wizard is a bit confusing. The wizard starts, then I can update the project details; then the data downloads, I can edit the data and then upload the edited data. But the wizard window needs to open the whole time. I would expect that you download a project edit data in QGIS and then when you're done you upload your changes. 

It seems that it is different with mockup
see : https://github.com/kartoza/cadasta-qgis-plugin/issues/23

**Comment by cchristelis** [comment]
So if there is a project already loaded in memory it should use that project rather than try and download a new one? Perhaps we should require the user to use the downloader before the wizard starts?

**Comment by dimasciput** [comment]
Update wizard has been updated
