### ISSUE TITLE
Download and join relationship and party attributes

### ISSUE THREAD

**Issue by meomancer** [Cadasta/cadasta-qgis-plugin#89]
Oliver's question:

> Related to this is the project download option. You can download a project but only look at it, but there's no way to update anything. Also, is there a way to download and join relationship and party attributes?

**Comment by oliverroick** [comment]
Regarding our discussions this morning about the m:n-relationships to relationships and parties:

One thing that came to my mind that might help in this case is thinking of relationship and party data as CSVs. In QGIS, you can add CSV files to your list of layers and view and edit like any other attribute table, they are just not shown on the map. This is the way we handle this problem in exports: You get a Shapefile and CSVs for parties and relationships. 

![screen shot 2017-02-08 at 16 42 55](https://cloud.githubusercontent.com/assets/159510/22744643/32a10974-ee1e-11e6-9d47-c99b269ee571.png)

Would that be a feasible way forward?

**Comment by dimasciput** [comment]
Thanks @oliverroick , we will look into it today.

**Comment by dimasciput** [comment]
Hi @oliverroick I addressed this issue in https://github.com/kartoza/cadasta-qgis-plugin/pull/102 with different layer for relationships and parties, here's the screencast : 

![cadasta](https://cloud.githubusercontent.com/assets/1979569/22819924/17e04c96-efa7-11e6-9df9-e05002072d53.gif)

**Comment by oliverroick** [comment]
Looks good! Nice work.
