### ISSUE TITLE
about attributes in JSON format

### ISSUE THREAD

**Issue by meomancer** [Cadasta/cadasta-qgis-plugin#90]
# Problem
Oliver's question:

> The attributes are shown as JSON in the attribute table. Will that be changed, so each field in the JSON is a separate field in the attribute table? 

# Solution
Yes, we can parse it. Although for geojson, the correct way is bring all of attributes json to just in properties. So it is separate properties.

**Comment by timlinux** [comment]
@cchristelis This sounds like the thing I flagged with you guys where the JSON raw value were not being split out into their own fields.....it is the same issue @meomancer ?

**Comment by cchristelis** [comment]
exactly @timlinux. So @meomancer, we need to convert from json to attributes table and vice versa.
